# @name Ordrelinje med vedtak infotrygd og hjelpemiddeltype="Hjelpemiddel"
### Ordrelinje med vedtak infotrygd og hjelpemiddeltype="Hjelpemiddel"
POST {{ingress}}/push
Content-Type: application/json
Authorization: Bearer {{oebstoken}}

{
  "System": "DIGIHOT",
  "Id": 205,
  "IncidentNummer": 1,
  "IncidentStatus": "Closed",
  "IncidentType": "Vedtak Infotrygd",
  "IncidentSoknadType": "HJDASK",
  "IncidentVedtakDato": "{{vedtaksDato}}",
  "IncidentSoknad": "S",
  "IncidentResultat": "I",
  "IncidentRef": "{{infotrygdSaksblokkOgSaksnr}}",
  "ReferanseNummer": "",
  "Kilde": "",
  "OrdreNumber": 1,
  "LineNumber": 1,
  "ShipmentNumber": 1,
  "CategoryDescription": "Rollatorer, 4 hjul utebruk",
  "OrderedItem": "286589",
  "CategoryNum": "1",
  "User_ItemType": "Hjelpemiddel",
  "Quantity": 1,
  "ShippingQuantityUom": "STK",
  "AccountNumber": "{{fnr}}",
  "EgenAnsatt": "N",
  "LastUpdateDate": "{{sistOppdatertDato}}",
  "Description": "Topro Olympos ATR M",
  "SendTilAddresse1": "{{sendtTilAdresse}}"
}

### Ordrelinje med vedtak infotrygd og hjelpemiddeltype="Hjelpemiddel" + serienumre
POST {{ingress}}/push
Content-Type: application/json
Authorization: Bearer {{oebstoken}}

{
  "System": "DIGIHOT",
  "Id": 230,
  "IncidentNummer": 1,
  "IncidentStatus": "Closed",
  "IncidentType": "Vedtak Infotrygd",
  "IncidentSoknadType": "HJDASK",
  "IncidentVedtakDato": "{{vedtaksDato}}",
  "IncidentSoknad": "S",
  "IncidentResultat": "I",
  "IncidentRef": "{{infotrygdSaksblokkOgSaksnr}}",
  "ReferanseNummer": "",
  "Kilde": "",
  "OrdreNumber": 1,
  "LineNumber": 1,
  "ShipmentNumber": 1,
  "CategoryDescription": "Rollatorer, 4 hjul utebruk",
  "OrderedItem": "286589",
  "SerieNummerListe":["123456", "654321"],
  "CategoryNum": "1",
  "User_ItemType": "Hjelpemiddel",
  "Quantity": 2,
  "ShippingQuantityUom": "STK",
  "AccountNumber": "{{fnr}}",
  "EgenAnsatt": "N",
  "LastUpdateDate": "{{sistOppdatertDato}}",
  "Description": "Topro Olympos ATR M",
  "SendTilAddresse1": "{{sendtTilAdresse}}"
}

### Ordrelinje med vedtak infotrygd og hjelpemiddeltype="Del"
POST {{ingress}}/push
Content-Type: application/json
Authorization: Bearer {{oebstoken}}

{
  "System": "DIGIHOT",
  "Id": 1,
  "IncidentNummer": 1,
  "IncidentStatus": "Closed",
  "IncidentType": "Vedtak Infotrygd",
  "IncidentSoknadType": "HJDASK",
  "IncidentVedtakDato": "{{vedtaksDato}}",
  "IncidentSoknad": "S",
  "IncidentResultat": "I",
  "IncidentRef": "{{infotrygdSaksblokkOgSaksnr}}",
  "ReferanseNummer": "",
  "Kilde": "",
  "OrdreNumber": 1,
  "LineNumber": 2,
  "ShipmentNumber": 1,
  "CategoryDescription": "Tilbehør Rollatorer",
  "OrderedItem": "286593",
  "CategoryNum": "1",
  "User_ItemType": "Del",
  "Quantity": 1,
  "ShippingQuantityUom": "STK",
  "AccountNumber": "{{fnr}}",
  "EgenAnsatt": "N",
  "LastUpdateDate": "{{sistOppdatertDato}}",
  "Description": "Offroad-hjul rullator 4hjul Topro Olympos ATR sett á fire hjul",
  "SendTilAddresse1": "{{sendtTilAdresse}}"
}

### Ordrelinje med vedtak hotsak og hjelpemiddeltype="Hjelpemiddel"
POST {{ingress}}/push
Content-Type: application/json
Authorization: Bearer {{oebstoken}}

{
  "System": "DIGIHOT",
  "Id": 307,
  "IncidentNummer": 1,
  "IncidentStatus": "Closed",
  "IncidentType": "Vedtak Infotrygd",
  "IncidentSoknadType": "HJDASK",
  "IncidentVedtakDato": "{{vedtaksDato}}",
  "IncidentSoknad": "S",
  "IncidentResultat": "I",
  "IncidentRef": "",
  "ReferanseNummer": "{{hotsakSaksnummer}}",
  "Kilde": "HOTSAK",
  "OrdreNumber": 1,
  "LineNumber": 1,
  "ShipmentNumber": 1,
  "CategoryDescription": "Rollatorer, 4 hjul utebruk",
  "OrderedItem": "014112",
  "CategoryNum": "1",
  "User_ItemType": "Hjelpemiddel",
  "Quantity": 1,
  "ShippingQuantityUom": "STK",
  "ShippingInstructions": "Pute kommer fra Nimacare til dere",
  "AccountNumber": "{{fnr}}",
  "EgenAnsatt": "N",
  "LastUpdateDate": "{{sistOppdatertDato}}",
  "Description": "Topro Terskeleliminator",
  "SerieNummerListe":["123456", "654321"],
  "SendTilAddresse1": "{{sendtTilAdresse}}"
}

### Ordrelinje med vedtak hotsak og hjelpemiddeltype="Del"
POST {{ingress}}/push
Content-Type: application/json
Authorization: Bearer {{oebstoken}}

{
  "System": "DIGIHOT",
  "Id": 1,
  "IncidentNummer": 1,
  "IncidentStatus": "Closed",
  "IncidentType": "Vedtak Infotrygd",
  "IncidentSoknadType": "HJDASK",
  "IncidentVedtakDato": "{{vedtaksDato}}",
  "IncidentSoknad": "S",
  "IncidentResultat": "I",
  "IncidentRef": "",
  "ReferanseNummer": "{{hotsakSaksnummer}}",
  "Kilde": "HOTSAK",
  "OrdreNumber": 1,
  "LineNumber": 2,
  "ShipmentNumber": 1,
  "CategoryDescription": "Tilbehør Rollatorer",
  "OrderedItem": "286593",
  "CategoryNum": "1",
  "User_ItemType": "Del",
  "Quantity": 1,
  "ShippingQuantityUom": "STK",
  "AccountNumber": "{{fnr}}",
  "EgenAnsatt": "N",
  "LastUpdateDate": "{{sistOppdatertDato}}",
  "Description": "Offroad-hjul rullator 4hjul Topro Olympos ATR sett á fire hjul",
  "SendTilAddresse1": "{{sendtTilAdresse}}"
}

###
