apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-oebs-listener
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  kafka:
    pool: nav-dev
  envFrom:
    - secret: hm-oebs-listener-secret
    - secret: hm-influxdb-secret
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 50m
      memory: 600Mi
  liveness:
    path: /isalive
  readiness:
    path: /isready
  ingresses:
    - https://hm-oebs-listener.intern.dev.nav.no
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: hooks.slack.com
