apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-oebs-listener
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  kafka:
    pool: nav-prod
  envFrom:
    - secret: hm-oebs-listener-secret
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 50m
      memory: 600Mi
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  port: 8080
  ingresses:
    - https://hm-oebs-listener.intern.nav.no
  accessPolicy:
    outbound:
      external:
        - host: hooks.slack.com
        - application: logging
          namespace: nais-system
  env:
    - name: OEBS_LISTENER_LOG_LEVEL
      value: DEBUG
    - name: NTFY_URL
      value: https://ntfy.sh
    - name: NTFY_TOPIC
      value: teamdigihot_hm-oebs-listener
