package no.nav.hjelpemidler.oebs.listener.model

import com.fasterxml.jackson.annotation.JsonFormat
import java.time.LocalDate

data class RåOrdrelinje(
    val mottakendeSystem: String,
    val oebsId: Int,
    val serviceforespørsel: Int,
    val serviceforespørselstatus: String,
    val serviceforespørseltype: String,
    val søknadstype: String,
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    val vedtaksdato: LocalDate?,
    val søknad: String,
    val hotSakSaksnummer: String?,
    val kilde: String?,
    val resultat: String,
    val saksblokkOgSaksnr: String?,
    val ordrenr: Int,
    val ordrelinje: Int,
    val delordrelinje: Int,
    val artikkelbeskrivelse: String,
    val skipningsinstrukser: String?,
    val produktgruppe: String,
    val produktgruppeNr: String,
    val artikkelnr: String,
    val hjelpemiddeltype: String,
    val antall: Double,
    val enhet: String,
    val fnrBruker: String,
    val egenAnsatt: String,
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    val sistOppdatert: LocalDate,
    val sendtTilAdresse: String,
    var serienumre: List<String> = emptyList(),
    val utlånsstatistikk: List<Utlånsstatistikk> = emptyList(),
) {
    constructor(oebs: OrdrelinjeOebs) : this(
        mottakendeSystem = oebs.mottakendeSystem,
        oebsId = oebs.oebsId,
        serviceforespørsel = oebs.serviceforespørsel,
        serviceforespørselstatus = oebs.serviceforespørselstatus,
        serviceforespørseltype = oebs.serviceforespørseltype,
        søknadstype = oebs.søknadstype,
        vedtaksdato = oebs.vedtaksdato,
        søknad = oebs.søknad,
        hotSakSaksnummer = oebs.hotSakSaksnummer,
        kilde = oebs.kilde,
        resultat = oebs.resultat,
        saksblokkOgSaksnr = oebs.saksblokkOgSaksnr,
        ordrenr = oebs.ordrenr,
        ordrelinje = oebs.ordrelinje,
        delordrelinje = oebs.delordrelinje,
        artikkelbeskrivelse = oebs.artikkelbeskrivelse,
        skipningsinstrukser = oebs.skipningsinstrukser,
        produktgruppe = oebs.produktgruppe,
        produktgruppeNr = oebs.produktgruppeNr,
        artikkelnr = oebs.artikkelnr,
        hjelpemiddeltype = oebs.hjelpemiddeltype,
        antall = oebs.antall,
        enhet = oebs.enhet,
        fnrBruker = oebs.fnrBruker,
        egenAnsatt = oebs.egenAnsatt,
        sistOppdatert = oebs.sistOppdatert,
        sendtTilAdresse = oebs.sendtTilAdresse,
        serienumre = oebs.serienumre ?: emptyList(),
        utlånsstatistikk = oebs.utlånsstatistikk(),
    )
}
