name: Deploy til prod

on:
  release:
    types: [ published ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      id-token: "write"

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Nais login
        uses: nais/login@v0
        id: nais-login
        with:
          team: teamdigihot
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Lag miljøvariabel IMAGE
        env:
          VERSION_TAG: ${{ github.event.release.tag_name }}
          REGISTRY: ${{ steps.nais-login.outputs.registry }}
          APP: ${{ github.event.repository.name }}
        run: |
          IMAGE=$REGISTRY/$APP:$VERSION_TAG
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo $IMAGE

      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml

      - name: Post production
        uses: navikt/digihot-deploy/actions/post-production@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
